### ISSUE TITLE
Permission denied error using pynco ncks on windows

### ISSUE THREAD

**Issue by SusGrita** [nco/pynco#48]
Hello,
I am a beginner in Python and a new user of pynco. I am trying to write a small scripts that reads through a directory and creates a spatial subset of each file. The last command raises and error related to permissions. However, when I check the folder where the output files should be saved, I see that these have been generated, and when opened they seen alright. Does anyone have an idea of what the issue might be? 
Here is my script:
```
import os
from nco import Nco
from nco import custom as c
nco = Nco()

in_dir = r"D:\02_Portfolios\01_CCCM_Shelter\06_NaturalHazards\01_TropicalCyclones&StormSurge\ERA5-INTERIM"
out_dir = r"D:\02_Portfolios\01_CCCM_Shelter\06_NaturalHazards\01_TropicalCyclones&StormSurge\Work\outputs" 
os.chdir(in_dir)
path = os.getcwd()

# Create a subset of the NetCDF files
opt = [
        c.Limit(dmn_name="longitude", srt=42.304738, end=78.091223).prn_option(),
        c.Limit(dmn_name="latitude", srt=-11.534835, end=20.098029).prn_option()]
		
for f in os.listdir(path):
    f_split = os.path.split(f)[1]
#    iname = os.path.join(in_dir,f)
    out_f = os.path.join("temp",f_split.split('.')[0] + "_NorthIndian.nc")
    subset = nco.ncks(input=f, output=out_f, options=opt)
```
and this is the error I get:
```
Error in calling operator ncks with:
>>> C:\Users\reach\anaconda3\Library\bin\ncks -d longitude,42.304738,78.091223 -d latitude,-11.534835,20.098029 --output=temp\temp_NorthIndian.nc temp <<<
Inputs: temp
b'nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__open()\r\nnco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"\r\n'
Traceback (most recent call last):
  File "D:\02_Portfolios\01_CCCM_Shelter\06_NaturalHazards\01_TropicalCyclones&StormSurge\Work\TropicalCyclones\Python\WindSpeed.py", line 21, in <module>
    subset = nco.ncks(input=f, output=out_f, options=opt)
  File "C:\Users\reach\anaconda3\lib\site-packages\nco\nco.py", line 342, in get
    raise NCOException(**retvals)
nco.nco.NCOException: (returncode:1) b'nco_err_exit(): ERROR Short NCO-generated message (usually name of function that triggered error): nco__open()\r\nnco_err_exit(): ERROR Error code is 13. Translation into English with nc_strerror(13) is "Permission denied"\r\n'
```
Thank you very much in advance for your help!

**Comment by jhamman** [comment]
see #42 for conversation on windows support.

**Comment by czender** [comment]
This request has gone stale. Closing.
