### ISSUE TITLE
initialization issue

### ISSUE THREAD

**Issue by pranav-manik** [nco/pynco#54]
recieveing an issue in my django app on initialization
from nco import Nco
nco = Nco()

```
File "/**/***/***.py", line 46, in mergeDailyFile
    nco = Nco()
  File "/**/***/***/env/lib/python3.8/site-packages/nco/nco.py", line 58, in __init__
    self.nco_path = os.path.split(distutils.spawn.find_executable("ncks"))[0]
  File "/usr/lib/python3.8/posixpath.py", line 103, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by czender** [comment]
This is beyond my ken. Perhaps @hmb1 understands how to solve this...

**Comment by hmb1** [comment]
@pranav-manik
What version of Python are you using ? 
And what version of pynco version ?

**Comment by pranav-manik** [comment]
python 3.8 and pynco 1.0.0 but I also tried the same thing in a python dockerized 3.7 version with the following dependencies and recieved the same issue

```
numpy==1.16.5
scipy==1.7.1
netCDF4==1.5.6
```
```
Traceback (most recent call last):
  File "./test.py", line 4, in <module>
    nco = Nco()
  File "/usr/local/lib/python3.7/site-packages/nco/nco.py", line 58, in __init__
    self.nco_path = os.path.split(distutils.spawn.find_executable("ncks"))[0]
  File "/usr/local/lib/python3.7/posixpath.py", line 107, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by hmb1** [comment]
@pranav-manik
Erm  Do you have NCO in your PATH ?
I also suggest you netCDF pull the latest pynco from  here.

**Comment by pranav-manik** [comment]
I had not done a _sudo apt install nco_ as well, just a pip installation
